services:
  postgres:
    image: postgres
    environment:
      TZ: ${OS_TIMEZONE}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - ${DBMS_PORT}:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: migport@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Password123
    depends_on:
      - postgres

volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga
